import { afterAll, beforeAll, expect, it, vi } from 'vitest';
import { db } from '@/lib/db';
import { withBusiness } from '@/lib/tenant';
import { ingestProviderEvents } from '@/server/services/delivery-status-service';
import { emailConditionState } from '@/server/automations/email-condition';
import { createBusiness, destroyBusiness } from './helpers';
vi.mock('@/lib/events', async original => ({ ...await original<object>(), kickEventProcessing: vi.fn() }));
let tenant: Awaited<ReturnType<typeof createBusiness>>;
beforeAll(async () => { tenant = await createBusiness('journey-email-events'); });
afterAll(async () => { if (tenant) await destroyBusiness(tenant.business.id, [tenant.account.id]); });
it('persists an exact click URL from a provider event, deduplicates it and only opens the matching journey gate', async () => {
  const businessId = tenant.business.id;
  const credential = await db.providerCredential.create({ data: { businessId, channel: 'email', provider: 'resend', config: {} } });
  const contact = await db.contact.create({ data: { businessId, fullName: 'Email QA', phoneE164: '+972509990011', phoneRaw: '0509990011', email: 'qa@example.test' } });
  const conversation = await db.conversation.create({ data: { businessId, contactId: contact.id, channel: 'email', providerCredentialId: credential.id } });
  const start = new Date('2026-01-01T10:00:00Z'), clicked = new Date('2026-01-01T10:15:00Z');
  const message = await db.message.create({ data: { businessId, conversationId: conversation.id, channel: 'email', direction: 'OUTBOUND', type: 'TEXT', status: 'SENT', providerCredentialId: credential.id, providerMessageId: 'qa-email-provider', requestKey: 'seq:email-run:0', createdAt: start, acceptedAt: start } });
  const run = { id: 'email-run', contactId: contact.id }, condition = { sourceStep: 0, event: 'clicked' as const, timeoutMinutes: 60, link: 'https://example.com/offer' };
  const state = (c = condition) => withBusiness(businessId, () => emailConditionState(run, c, clicked));
  expect(await state()).toBe('waiting');
  const event = { kind: 'status' as const, status: 'CLICKED' as const, providerMessageId: message.providerMessageId!, eventId: `${businessId}:click`, at: clicked, link: condition.link };
  expect(await ingestProviderEvents(credential, [event])).toMatchObject([{ outcome: 'engagement' }]);
  expect(await ingestProviderEvents(credential, [event])).toMatchObject([{ outcome: 'duplicate' }]);
  expect(await state()).toBe('matched');
  expect(await state({ ...condition, link: 'https://example.com/other' })).toBe('waiting');
  expect(await withBusiness(businessId, () => emailConditionState({ ...run, id: 'different-run' }, condition, clicked))).toBe('missing');
  expect(await db.domainEvent.count({ where: { businessId, type: 'email.engagement' } })).toBe(1);
  expect((await db.message.findUniqueOrThrow({ where: { id: message.id } })).clickedAt).toEqual(clicked);
});
