-- Row-level security for every business-owned table + Account.sessionVersion (session invalidation on password change).
-- Runtime role: the application switches to it transaction-locally (src/lib/db-rls.ts) whenever a business context is active.
-- The connection owner keeps full access for login, webhook routing, cron enumeration and migrations.

ALTER TABLE "accounts" ADD COLUMN "session_version" INTEGER NOT NULL DEFAULT 0;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ultracrm_runtime') THEN CREATE ROLE ultracrm_runtime NOLOGIN NOBYPASSRLS NOINHERIT; END IF; END $$;
GRANT ultracrm_runtime TO CURRENT_USER;
GRANT USAGE ON SCHEMA public TO ultracrm_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ultracrm_runtime;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ultracrm_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ultracrm_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ultracrm_runtime;

ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "users";
-- users: the signed-in account may read its own memberships in other businesses (business switcher); writes stay tenant-bound.
CREATE POLICY tenant_isolation ON "users" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true) OR "account_id" = current_setting('app.account_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "teams";
CREATE POLICY tenant_isolation ON "teams" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "usage_counters" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "usage_counters";
CREATE POLICY tenant_isolation ON "usage_counters" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "contacts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "contacts";
CREATE POLICY tenant_isolation ON "contacts" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "contact_phones" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "contact_phones";
CREATE POLICY tenant_isolation ON "contact_phones" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "contact_emails" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "contact_emails";
CREATE POLICY tenant_isolation ON "contact_emails" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "tags";
CREATE POLICY tenant_isolation ON "tags" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "leads";
CREATE POLICY tenant_isolation ON "leads" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "deals" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "deals";
CREATE POLICY tenant_isolation ON "deals" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "tasks";
CREATE POLICY tenant_isolation ON "tasks" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "notes" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "notes";
CREATE POLICY tenant_isolation ON "notes" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "suppressions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "suppressions";
CREATE POLICY tenant_isolation ON "suppressions" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "dnc_entries" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "dnc_entries";
CREATE POLICY tenant_isolation ON "dnc_entries" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "domain_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "domain_events";
CREATE POLICY tenant_isolation ON "domain_events" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "automation_jobs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "automation_jobs";
CREATE POLICY tenant_isolation ON "automation_jobs" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "audit_logs";
CREATE POLICY tenant_isolation ON "audit_logs" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "dial_lists" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "dial_lists";
CREATE POLICY tenant_isolation ON "dial_lists" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "list_leads" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "list_leads";
CREATE POLICY tenant_isolation ON "list_leads" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "dialer_sessions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "dialer_sessions";
CREATE POLICY tenant_isolation ON "dialer_sessions" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "calls" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "calls";
CREATE POLICY tenant_isolation ON "calls" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "call_monitors" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "call_monitors";
CREATE POLICY tenant_isolation ON "call_monitors" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "telephony_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "telephony_events";
CREATE POLICY tenant_isolation ON "telephony_events" TO ultracrm_runtime USING (("business_id" IS NULL OR "business_id" = current_setting('app.business_id', true))) WITH CHECK (("business_id" IS NULL OR "business_id" = current_setting('app.business_id', true)));
ALTER TABLE "phone_numbers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "phone_numbers";
CREATE POLICY tenant_isolation ON "phone_numbers" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "scripts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "scripts";
CREATE POLICY tenant_isolation ON "scripts" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "note_drafts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "note_drafts";
CREATE POLICY tenant_isolation ON "note_drafts" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "provider_credentials" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "provider_credentials";
CREATE POLICY tenant_isolation ON "provider_credentials" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "whatsapp_signup_sessions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "whatsapp_signup_sessions";
CREATE POLICY tenant_isolation ON "whatsapp_signup_sessions" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "conversations";
CREATE POLICY tenant_isolation ON "conversations" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "messages";
CREATE POLICY tenant_isolation ON "messages" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "conversation_drafts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "conversation_drafts";
CREATE POLICY tenant_isolation ON "conversation_drafts" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "canned_replies" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "canned_replies";
CREATE POLICY tenant_isolation ON "canned_replies" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "templates" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "templates";
CREATE POLICY tenant_isolation ON "templates" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "automation_rules" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "automation_rules";
CREATE POLICY tenant_isolation ON "automation_rules" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "automation_runs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "automation_runs";
CREATE POLICY tenant_isolation ON "automation_runs" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "distribution_lists" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "distribution_lists";
CREATE POLICY tenant_isolation ON "distribution_lists" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "campaigns" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "campaigns";
CREATE POLICY tenant_isolation ON "campaigns" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "provider_webhook_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "provider_webhook_events";
CREATE POLICY tenant_isolation ON "provider_webhook_events" TO ultracrm_runtime USING (("business_id" IS NULL OR "business_id" = current_setting('app.business_id', true))) WITH CHECK (("business_id" IS NULL OR "business_id" = current_setting('app.business_id', true)));
ALTER TABLE "marketing_sequences" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "marketing_sequences";
CREATE POLICY tenant_isolation ON "marketing_sequences" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "sequence_runs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "sequence_runs";
CREATE POLICY tenant_isolation ON "sequence_runs" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "number_connections" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "number_connections";
CREATE POLICY tenant_isolation ON "number_connections" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));
ALTER TABLE "number_orders" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "number_orders";
CREATE POLICY tenant_isolation ON "number_orders" TO ultracrm_runtime USING ("business_id" = current_setting('app.business_id', true)) WITH CHECK ("business_id" = current_setting('app.business_id', true));

-- Child tables without business_id: visible/writable only through a parent row of the current business.
ALTER TABLE "campaign_recipients" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "campaign_recipients";
CREATE POLICY tenant_isolation ON "campaign_recipients" TO ultracrm_runtime USING (EXISTS (SELECT 1 FROM "campaigns" p WHERE p."id" = "campaign_recipients"."campaign_id" AND p."business_id" = current_setting('app.business_id', true))) WITH CHECK (EXISTS (SELECT 1 FROM "campaigns" p WHERE p."id" = "campaign_recipients"."campaign_id" AND p."business_id" = current_setting('app.business_id', true)));
ALTER TABLE "contact_tags" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "contact_tags";
CREATE POLICY tenant_isolation ON "contact_tags" TO ultracrm_runtime USING (EXISTS (SELECT 1 FROM "contacts" p WHERE p."id" = "contact_tags"."contact_id" AND p."business_id" = current_setting('app.business_id', true))) WITH CHECK (EXISTS (SELECT 1 FROM "contacts" p WHERE p."id" = "contact_tags"."contact_id" AND p."business_id" = current_setting('app.business_id', true)));
ALTER TABLE "conversation_tags" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "conversation_tags";
CREATE POLICY tenant_isolation ON "conversation_tags" TO ultracrm_runtime USING (EXISTS (SELECT 1 FROM "conversations" p WHERE p."id" = "conversation_tags"."conversation_id" AND p."business_id" = current_setting('app.business_id', true))) WITH CHECK (EXISTS (SELECT 1 FROM "conversations" p WHERE p."id" = "conversation_tags"."conversation_id" AND p."business_id" = current_setting('app.business_id', true)));
ALTER TABLE "dial_list_agents" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "dial_list_agents";
CREATE POLICY tenant_isolation ON "dial_list_agents" TO ultracrm_runtime USING (EXISTS (SELECT 1 FROM "dial_lists" p WHERE p."id" = "dial_list_agents"."list_id" AND p."business_id" = current_setting('app.business_id', true))) WITH CHECK (EXISTS (SELECT 1 FROM "dial_lists" p WHERE p."id" = "dial_list_agents"."list_id" AND p."business_id" = current_setting('app.business_id', true)));
ALTER TABLE "distribution_list_members" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "distribution_list_members";
CREATE POLICY tenant_isolation ON "distribution_list_members" TO ultracrm_runtime USING (EXISTS (SELECT 1 FROM "distribution_lists" p WHERE p."id" = "distribution_list_members"."list_id" AND p."business_id" = current_setting('app.business_id', true))) WITH CHECK (EXISTS (SELECT 1 FROM "distribution_lists" p WHERE p."id" = "distribution_list_members"."list_id" AND p."business_id" = current_setting('app.business_id', true)));
ALTER TABLE "message_attachments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "message_attachments";
CREATE POLICY tenant_isolation ON "message_attachments" TO ultracrm_runtime USING (EXISTS (SELECT 1 FROM "messages" p WHERE p."id" = "message_attachments"."message_id" AND p."business_id" = current_setting('app.business_id', true))) WITH CHECK (EXISTS (SELECT 1 FROM "messages" p WHERE p."id" = "message_attachments"."message_id" AND p."business_id" = current_setting('app.business_id', true)));
ALTER TABLE "sequence_steps" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "sequence_steps";
CREATE POLICY tenant_isolation ON "sequence_steps" TO ultracrm_runtime USING (EXISTS (SELECT 1 FROM "marketing_sequences" p WHERE p."id" = "sequence_steps"."sequence_id" AND p."business_id" = current_setting('app.business_id', true))) WITH CHECK (EXISTS (SELECT 1 FROM "marketing_sequences" p WHERE p."id" = "sequence_steps"."sequence_id" AND p."business_id" = current_setting('app.business_id', true)));
